version: '3.1'

services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: words_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    expose:
      - 3306

  test_task:
    build:
      context: .
    image: "test_task"
    restart: "no"
    ports:
      - 8080:8080
    links:
      - "db"
